name: Bestenlisten Download

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update raw data
        uses: actions/checkout@v4
      - run: |
          bash raw/2023/download.sh
          git config user.name Github Action
          git config user.email actions@github.com
          git add -A
          timestamp=$(date -u)
          git commit -m "update raw ladv data: ${timestamp}" || exit 0
          git push